---
title: "Dev-data-product-project"
author: "Amir"
date: "15 5 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The ui.R

```{r}

library(shiny)

# Define UI for application
shinyUI(fluidPage(

    # Application title
    titlePanel("Dev data product project"),

    # Sidebar with the slop
    sidebarLayout(
        sidebarPanel(
            h3("slope"),
            textOutput("slopOut"),
        ),

        # The main panel with a plot of mile per galn by weight
        mainPanel(
            plotOutput("plot1", brushOpts(
                id = "brush1"
            ))
        )
    )
))
```

## The server.R

```{r}

library(shiny)

# Define server logic required to draw a scatter plot
shinyServer(function(input, output) {
# Creating a linear model of the mpg by wt
    model <-  reactive({
    brushed_data <- brushedPoints(mtcars, input$brush1,
                                  xvar = "wt", yvar = "mpg")
    if(nrow(brushed_data) < 2){
        return(NULL)
    }
    lm(mpg ~ wt, data = brushed_data)
})
# return the slop of the linear model or "no model found"    
output$slopOut <- renderText({
    if(is.null(model())){
        "no model found"
    }
    else{
        model[1][2]
    }
})
#return a scatter plot of the mpg by wt
output$plot1 <- renderPlot({
    plot(mtcars$wt, mtcars$mpg, xlab = "wt", ylab = "mpg", main = "mile per galan by weight")
})})

```
